version: "3.7"

services:
  sedig:
    container_name: sedig-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8089:8080"
    command: >
      bash -c "
          yarn install
          yarn serve
          yarn global add @vue/cli"

# networks:
#   default:
#       name: sedig_front

networks:
  sedig_front:
    driver: bridge
    name: sedig_front
    driver_opts:
      com.docker.compose.network: "sedig_front" # Certifique-se de que a etiqueta esteja definida corretamente aqui
